##
# Android-Specific Cross-Compiler Configuration
##
CFLAGS += -Wall
CFLAGS += -Dandroid
CFLAGS += -I$(NDK_ARCH)/usr/include

NDK = ~/android/android-ndk-r4
NDK_ARCH = $(NDK)/build/platforms/android-3/arch-arm

CURRENT_SYSTEM = $(shell uname -s | tr A-Z a-z)
CROSS_COMPILE = $(NDK)/build/prebuilt/$(CURRENT_SYSTEM)-x86/arm-eabi-4.2.1/bin/arm-eabi-

CC = $(CROSS_COMPILE)gcc

# Local Variables:
# mode: makefile
# End: