/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_wlanlj_meshapp_OlsrNative */

#ifndef _Included_net_wlanlj_meshapp_OlsrNative
#define _Included_net_wlanlj_meshapp_OlsrNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_wlanlj_meshapp_OlsrNative
 * Method:    startOlsr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_OlsrNative_startOlsr
  (JNIEnv *, jobject);

/*
 * Class:     net_wlanlj_meshapp_OlsrNative
 * Method:    stopOlsr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_OlsrNative_stopOlsr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
