/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_wlanlj_meshapp_GuiLibTask */

#ifndef _Included_net_wlanlj_meshapp_GuiLibTask
#define _Included_net_wlanlj_meshapp_GuiLibTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_wlanlj_meshapp_GuiLibTask
 * Method:    startOlsrd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_GuiLibTask_startOlsrd
  (JNIEnv *, jclass);

/*
 * Class:     net_wlanlj_meshapp_GuiLibTask
 * Method:    stopOlsrd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_GuiLibTask_stopOlsrd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
