/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_wlanlj_meshapp_OlsrNative */

#ifndef _Included_net_wlanlj_meshapp_OlsrNative
#define _Included_net_wlanlj_meshapp_OlsrNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_wlanlj_meshapp_OlsrNative
 * Method:    startOlsrd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_OlsrNative_startOlsrd
  (JNIEnv *, jclass);

/*
 * Class:     net_wlanlj_meshapp_OlsrNative
 * Method:    stopOlsrd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_OlsrNative_stopOlsrd
  (JNIEnv *, jclass);

/*
 * Class:     net_wlanlj_meshapp_OlsrNative
 * Method:    generateConfigFile
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_OlsrNative_generateConfigFile
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
