/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_wlanlj_meshapp_OlsrNative */

#ifndef _Included_net_wlanlj_meshapp_OlsrNative
#define _Included_net_wlanlj_meshapp_OlsrNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_wlanlj_meshapp_OlsrNative
 * Method:    getProp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_wlanlj_meshapp_OlsrNative_getProp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_wlanlj_meshapp_OlsrNative
 * Method:    runCommand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_OlsrNative_runCommand
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
