/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_wlanlj_meshapp_GuiLibTask */

#ifndef _Included_net_wlanlj_meshapp_GuiLibTask
#define _Included_net_wlanlj_meshapp_GuiLibTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_wlanlj_meshapp_GuiLibTask
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_GuiLibTask_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_wlanlj_meshapp_GuiLibTask
 * Method:    start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_GuiLibTask_start
  (JNIEnv *, jclass);

/*
 * Class:     net_wlanlj_meshapp_GuiLibTask
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_wlanlj_meshapp_GuiLibTask_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
