#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/stat.h>

#include "guilib.h"
#include "config.h"
#include "log.h"

#define OLSR_STOPPED  0
#define OLSR_RUNNING  1

const char *root_cmd = "su -c ";

int olsr_status = OLSR_STOPPED;

int init(const char *path)
{
  mode_t exec_mode = S_IRUSR | S_IWUSR | S_IXUSR | S_IRGRP | S_IWGRP | S_IXGRP | S_IROTH | S_IXOTH;

  /**
   * Set the file paths.
   */
  strcpy(platform_data_path, path);
  set_file_path(olsr_start_script, olsr_start_script_name);
  set_file_path(olsr_stop_script, olsr_stop_script_name);
  set_file_path(olsr_config_file, olsr_config_file_name);
  set_file_path(olsr_pid_file, olsr_pid_file_name);
  set_file_path(olsr_lock_file, olsr_lock_file_name);
  set_file_path(olsr_bin_file, olsr_bin_file_name);
  set_file_path(wificonfig_bin_file, wificonfig_bin_file_name);
  
  /**
   * Set executable permissions.
   */
  chmod(olsr_start_script, exec_mode);
  chmod(olsr_stop_script, exec_mode);
  chmod(olsr_bin_file, exec_mode);
  chmod(wificonfig_bin_file, exec_mode);

  /**
   * Print some debugging information.
   */
  get_uid();
  
  return 0;
}

int guilib_start(void)
{
  mode_t read_mode = S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH;
  
  /**
   * Scan for wireless ad-hoc networks, start olsrd on successful completion.
   */
  if (wifi_scan() != 0)
    return -1;

  if (olsrd_start() != 0)
    return -1;

  /**
   * Set permissions on temporary files generated by guilib at runtime.
   */
  chmod(olsr_pid_file, read_mode);
  chmod(olsr_config_file, read_mode);

  return 0;
}

int guilib_stop(void)
{
  if (olsrd_stop() != 0)
    return -1;
  
  /**
   * Remove temporary files.
   */ 
  clean_temp_files(olsr_pid_file);
  clean_temp_files(olsr_lock_file);
  clean_temp_files(olsr_config_file);

  return 0;
}

int wifi_scan(void)
{
 /**
   * Scan for wireless ad-hoc networks.
   */
  strcpy(wificonfig_syscmd, root_cmd);
  strcat(wificonfig_syscmd, wificonfig_bin_file);

  if (system(wificonfig_syscmd) != 0) {
    guilib_syslog(GUILIB_LOG_ERROR, "Error \"%s\" returned non-zero exit status: %s", wificonfig_syscmd, strerror(errno));
    guilib_syslog(GUILIB_LOG_ERROR, "Error! Wifi scan failed!");
    return -1;
  }

  guilib_syslog(GUILIB_LOG_INFO, "Command \"%s\" executed successfully.", wificonfig_syscmd);
  guilib_syslog(GUILIB_LOG_INFO, "Scanning for ad-hoc networks...");
  
  return 0;
}

int olsrd_start(void)
{  
  /**
   * Configure the OLSR routing protocol.
   */
  if (configure_olsr_protocol() == -1) {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! Failed to write OLSR config file %s: %s", olsr_config_file_name, strerror(errno));
    return -1;
  }
    
  guilib_syslog(GUILIB_LOG_INFO, "Wrote OLSR config file: %s", olsr_config_file);
  strcpy(olsr_start_syscmd, root_cmd);
  strcat(olsr_start_syscmd, olsr_start_script);
  
  /**
   * Run the script to start the OLSR daemon.
   */
  if (system(olsr_start_syscmd) != 0) {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! \"%s\" returned non-zero exit status: %s", olsr_start_syscmd, strerror(errno));
    return -1;
  }
  
  guilib_syslog(GUILIB_LOG_INFO, "Command \"%s\" executed successfully.", olsr_start_syscmd);
  guilib_syslog(GUILIB_LOG_INFO, "Started the OLSR daemon.");
}

int olsrd_stop(void)
{
  strcpy(olsr_stop_syscmd, root_cmd);
  strcat(olsr_stop_syscmd, olsr_stop_script);
  
  /**
   * Run the script to stop the OLSR daemon.
   */
  if (system(olsr_stop_syscmd) != 0) {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! \"%s\" returned non-zero exit status: %s", olsr_stop_syscmd, strerror(errno));
    return -1;
  }						
  
  guilib_syslog(GUILIB_LOG_INFO, "Command \"%s\" executed successfully.", olsr_stop_syscmd);
  guilib_syslog(GUILIB_LOG_INFO, "Stopped the OLSR daemon.");
    
  return 0;
}

void clean_temp_files(char *file_path) {
  if (remove(file_path) != 0)
    guilib_syslog(GUILIB_LOG_ERROR, "Error! Failed to remove temporary file \"%s\": %s", file_path, strerror(errno));
  else
    guilib_syslog(GUILIB_LOG_INFO, "Removed temporary file \"%s\"", file_path);
 
  return;
}


void get_uid()
{
  FILE *id;
  char line[BUFSIZE];

  id = popen("/system/bin/id", "r");

  if (id != NULL) {
    while (fgets(line, sizeof(line), id)) {
      guilib_syslog(GUILIB_LOG_INFO, "id: %s", line);
    }
    pclose(id);
  } else {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! Failed to open pipe: %s", strerror(errno));
  }
  return;    
}
