#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/stat.h>

#include "guilib.h"
#include "config.h"
#include "log.h"

const char *root_cmd = "su -c ";

int init(const char *path)
{
  /**
   * Set the file paths.
   */
  strcpy(platform_data_path, path);

  set_file_path(olsr_start_script, olsr_start_script_name);
  set_file_path(olsr_stop_script, olsr_stop_script_name);
  set_file_path(olsr_config_file, olsr_config_file_name);
  set_file_path(olsr_pid_file, olsr_pid_file_name);
  set_file_path(olsr_lock_file, olsr_lock_file_name);
  set_file_path(olsr_bin_file, olsr_bin_file_name);

  // write uid to the syslog for debugging.
  get_uid();
  
  /**
   * Set file permissions on scripts.
   */
  mode_t exec_mode = S_IRUSR | S_IWUSR | S_IXUSR | S_IRGRP | S_IWGRP | S_IXGRP | S_IROTH | S_IXOTH;
  
  chmod(olsr_start_script, exec_mode);
  chmod(olsr_stop_script, exec_mode);
  chmod(olsr_bin_file, exec_mode);
  
  return 0;
}

int meshapp_start()
{

  /**
   * Scan for ad-hoc networks.
   */
  wpa_open_control_connection("/data/misc/wifi/sockets");
  wpa_print_scan_results();
  
  /**
   * Configure the OLSR routing protocol.
   */
  if (configure_olsr_protocol() == -1) {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! Failed to write OLSR config file %s: %s", olsr_config_file_name, strerror(errno));
    return -1;
  }
  
  guilib_syslog(GUILIB_LOG_INFO, "Wrote OLSR config file: %s", olsr_config_file);

  /**
   * Run the script to start the OLSR daemon.
   */
  strcpy(olsr_start_syscmd, root_cmd);
  strcat(olsr_start_syscmd, olsr_start_script);
  
  if (system(olsr_start_syscmd) != 0) {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! \"%s\" returned non-zero exit status: %s", olsr_start_syscmd, strerror(errno));
    return -1;
  }

  guilib_syslog(GUILIB_LOG_INFO, "Command \"%s\" executed successfully.", olsr_start_syscmd);
  guilib_syslog(GUILIB_LOG_INFO, "Started the OLSR daemon.");

  /**
   * Set permissions on temporary files generated by guilib at runtime.
   */
  mode_t read_mode = S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH;
  
  chmod(olsr_pid_file, read_mode);
  chmod(olsr_config_file, read_mode);
  
  return 0;
}

int meshapp_stop()
{

  strcpy(olsr_stop_syscmd, root_cmd);
  strcat(olsr_stop_syscmd, olsr_stop_script);
 
 /**
   * Run the script to stop the OLSR daemon.
   */
  if (system(olsr_stop_syscmd) != 0) {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! \"%s\" returned non-zero exit status: %s", olsr_stop_syscmd, strerror(errno));
    return -1;
  }						
  
  guilib_syslog(GUILIB_LOG_INFO, "Command \"%s\" executed successfully.", olsr_stop_syscmd);
  guilib_syslog(GUILIB_LOG_INFO, "Stopped the OLSR daemon.");

  /**
   * Remove temporary files.
   */
 
  if (remove(olsr_pid_file) != 0) {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! Failed to remove temporary file \"%s\": %s", olsr_pid_file, strerror(errno));
    return -1;
  } 
  if (remove(olsr_lock_file) != 0) {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! Failed to remove temporary file \"%s\": %s", olsr_lock_file, strerror(errno));
    return -1;
  }
  if (remove(olsr_config_file) != 0) {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! Failed to remove temporary file \"%s\": %s", olsr_config_file, strerror(errno));
    return -1;
  }
    guilib_syslog(GUILIB_LOG_INFO, "Removed temporary file \"%s\".", olsr_pid_file);
    guilib_syslog(GUILIB_LOG_INFO, "Removed temporary file \"%s\".", olsr_lock_file);
    guilib_syslog(GUILIB_LOG_INFO, "Removed temporary file \"%s\".", olsr_config_file);
    
  return 0;
}

void get_uid()
{
  FILE *id;
  char line[BUFSIZE];

  id = popen("/system/bin/id", "r");

  if (id != NULL) {
    while (fgets(line, sizeof(line), id)) {
      guilib_syslog(GUILIB_LOG_INFO, "id: %s", line);
    }
    pclose(id);
  } else {
    guilib_syslog(GUILIB_LOG_ERROR, "Error! Failed to open pipe: %s", strerror(errno));
  }
  return;    
}
