
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <string.h>
#include <strings.h>
#include "olsrd_config.h"

void generate_olsr_config_file(void)
{
  
  FILE *cnf = fopen(config_file, "w");

  if (cnf != NULL) {
    printf("Generating config file %s\n", config_file);

    fprintf(cnf,"# olsrd.conf -- Automatically Generated by MeshApp.\n"
	    "DebugLevel \t 0\n"
	    "IpVersion \t 4\n"
	    "LockFile \"/data/data/net.wlanlj.meshapp/tmp/olsrd-ipv4.lock\"\n"
	    "Interface \t \"wlan0\"\n"
	    "{\n"
	    "\t Mode \"mesh\"\n"
	    "}\n");
  }
  
  fclose(cnf);
  return;
}


int get_olsr_pid(void)
{
  int olsr_pid;

  FILE *lck = fopen(lock_file, "r");
  
  if (lck != NULL) {
    fscanf(lck, "%d", &olsr_pid);
    return olsr_pid;
  }

  return -1;
}

int start_olsrd(void)
{
  const char *cmd = strcat("su -c olsrd -f", config_file);
  generate_olsr_config_file();
  if (system(cmd) > 0) {
    return 0;
  } else {
    return -1;
  }
}

int stop_olsrd(void)
{ 
  int olsr_pid = get_olsr_pid();
  remove(config_file);
  
  if (olsr_pid != -1 && kill(olsr_pid, 0) != 0)
    return kill(olsr_pid, SIGTERM);
  else
    return -1;
}
