/**
 *
 *  olsrd_config: A simple program for configuring and running olsrd under MeshApp.
 *  
 */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <string.h>
#include <strings.h>
#include "olsrd_config.h"

int generate_config_file(void)
{
  
  FILE *cnf = fopen(config_file, "w");

  if (cnf != NULL) {
    fprintf(cnf,"## olsrd.conf -- Automatically Generated by MeshApp\n"
	    "DebugLevel 0\n"
	    "IpVersion 4\n"
	    "Interface tiwlan0 {}");
    return 0;
  }

  return -1;
}




int get_olsr_pid(void)
{
  int olsr_pid;

  FILE *lck = fopen(lock_file, "r");
  
  if (lck != NULL) {
    fscanf(lck, "%d", &olsr_pid);
    return olsr_pid;
  }

  return -1;
}


int start_olsrd(void)
{
  if (generate_config_file() == 0) {
    const char *cmd = strcat("su -c olsrd -f", config_file);
    return system(cmd);
  } else {
    return system("su -c olsrd");
  }
}

int stop_olsrd(void)
{ 
  int olsr_pid = get_olsr_pid();
  remove(config_file);
  
  if (olsr_pid != -1 && kill(olsr_pid, 0) != 0)
    return kill(olsr_pid, SIGTERM);
  else
    return -1;
}
